#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
tools/generate-data.py

Reverse glyph data exporter for the custom SVG glyph format.

Reads:
  src/character-u{codepoint}.svg
  src/ligature-uXXXX-uYYYY(-uZZZZ...).svg

Writes:
  data/glyphs.json
  data/glyphs.py

What it extracts per glyph:
- character / codepoint metadata
- width / height (from SVG viewBox)
- raw polygon points
- rectangle form (x1,y1,x2,y2) when polygons are axis-aligned rectangles
- grid occupancy based on the known MMXX-style partition grid
  - singles use the standard X_BREAKS up to 20
  - ligatures use extended xBreaks in steps of 4 up to glyph width
- active cell coordinates

Ligatures:
- Stored separately in DATA["ligatures"].
- Keyed by sequence string like "u0073-u0074".
- Record also includes "key" (the actual character string, e.g. "st"),
  "sequence" (list of codepoints), and "sequenceKey" (string id).

This is designed to work with glyphs generated by your current SVG generator
(and also with manually edited/exported glyphs from the glyph designer).
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
import unicodedata
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from pprint import pformat
from typing import Any, Dict, List, Sequence, Tuple, Optional

# -----------------------------
# Known grid (from your typeface system)
# -----------------------------
# NOTE: Singles historically fit within 0..20; ligatures can be wider.
# We'll keep these as the canonical "single-glyph" breaks.
X_BREAKS = [0, 4, 8, 12, 16, 20]
Y_BREAKS = [0, 1, 4, 9, 10, 14, 15, 19, 20, 25, 29, 30]
CELL_H = 30
GRID_STEP_X = 4

# Small tolerance for float parsing / comparisons (in case edited SVGs contain "12.0")
EPS = 1e-9

CHAR_SVG_RE = re.compile(r"^character-u([0-9a-fA-F]+)\.svg$")
LIGA_SVG_RE = re.compile(
    r"^ligature-((?:u[0-9a-fA-F]+)(?:-u[0-9a-fA-F]+)+)\.svg$"
)

Point = Tuple[float, float]
Poly = List[Point]
Rect = Tuple[float, float, float, float]


@dataclass
class ParsedGlyph:
    kind: str                 # "char" or "liga"
    key: str                  # char kind: "u0061" ; liga kind: "u0073-u0074"
    char: str                 # char kind: "a" ; liga kind: "st" (may be multi-char)
    codepoint: Optional[int]  # char kind: 97 ; liga kind: None
    sequence: Optional[List[int]]  # char kind: None ; liga kind: [0x73,0x74]
    filename: str             # e.g. "character-u0061.svg" or "ligature-u0073-u0074.svg"
    width: float
    height: float
    polys: List[Poly]
    rects: List[Rect]
    warnings: List[str]


# -----------------------------
# Path helpers
# -----------------------------
def project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def default_src_dir() -> Path:
    return project_root() / "src"


def default_data_dir() -> Path:
    return project_root() / "data"


# -----------------------------
# Parsing helpers
# -----------------------------
def localname(tag: str) -> str:
    return tag.split("}", 1)[-1] if "}" in tag else tag


def parse_number(s: str) -> float:
    try:
        return float(s)
    except ValueError as e:
        raise ValueError(f"Invalid numeric value in SVG points: {s!r}") from e


def clean_num(n: float) -> int | float:
    """Convert integral floats to int for cleaner output."""
    if abs(n - round(n)) <= EPS:
        return int(round(n))
    return n


def parse_points_attr(points_attr: str) -> Poly:
    """
    Parse SVG polygon points:
      "x1,y1 x2,y2 x3,y3 ..."
    Also tolerates commas/spaces mixed.
    """
    tokens = points_attr.replace(",", " ").split()
    if len(tokens) % 2 != 0:
        raise ValueError(f"Odd number of coordinates in points attribute: {points_attr!r}")

    pts: Poly = []
    for i in range(0, len(tokens), 2):
        x = parse_number(tokens[i])
        y = parse_number(tokens[i + 1])
        pts.append((x, y))
    return pts


def parse_viewbox(root: ET.Element) -> Tuple[float, float, float, float]:
    vb = root.attrib.get("viewBox")
    if vb:
        parts = vb.replace(",", " ").split()
        if len(parts) != 4:
            raise ValueError(f"Invalid viewBox: {vb!r}")
        return tuple(parse_number(p) for p in parts)  # type: ignore[return-value]

    # Fallback to width/height if no viewBox (less ideal)
    w = root.attrib.get("width")
    h = root.attrib.get("height")
    if w is None or h is None:
        raise ValueError("SVG is missing both viewBox and width/height.")
    return (0.0, 0.0, parse_number(w), parse_number(h))


def is_axis_aligned_rect(poly: Poly) -> bool:
    if len(poly) != 4:
        return False
    xs = {round(p[0], 9) for p in poly}
    ys = {round(p[1], 9) for p in poly}
    return len(xs) == 2 and len(ys) == 2


def poly_to_rect(poly: Poly) -> Rect:
    xs = [p[0] for p in poly]
    ys = [p[1] for p in poly]
    return (min(xs), min(ys), max(xs), max(ys))


def _decode_ligature_filename(name: str) -> Tuple[str, List[int], str]:
    """
    ligature-u0073-u0074.svg -> ("st", [0x73,0x74], "u0073-u0074")
    """
    m = LIGA_SVG_RE.match(name)
    if not m:
        raise ValueError(f"Unsupported ligature filename: {name}")

    seq = m.group(1)  # "u0073-u0074"
    parts = seq.split("-")
    cps: List[int] = []
    chars: List[str] = []
    for part in parts:
        if not part.lower().startswith("u"):
            raise ValueError(f"Invalid ligature segment: {part!r} in {name}")
        cp = int(part[1:], 16)
        cps.append(cp)
        chars.append(chr(cp))
    return ("".join(chars), cps, seq.lower())


def parse_svg_file(svg_path: Path) -> ParsedGlyph:
    # Character glyph
    m = CHAR_SVG_RE.match(svg_path.name)
    if m:
        hex_cp = m.group(1).lower()
        cp = int(hex_cp, 16)
        ch = chr(cp)
        key = f"u{hex_cp}"

        text = svg_path.read_text(encoding="utf-8")
        root = ET.fromstring(text)

        min_x, min_y, width, height = parse_viewbox(root)
        warnings: List[str] = []

        if abs(min_x) > EPS or abs(min_y) > EPS:
            warnings.append(f"Non-zero viewBox origin ({min_x}, {min_y})")

        polys: List[Poly] = []
        rects: List[Rect] = []

        for elem in root.iter():
            if localname(elem.tag) != "polygon":
                continue
            points_attr = elem.attrib.get("points", "").strip()
            if not points_attr:
                warnings.append("Polygon without points attribute")
                continue

            poly = parse_points_attr(points_attr)
            polys.append(poly)

            if is_axis_aligned_rect(poly):
                rects.append(poly_to_rect(poly))
            else:
                warnings.append(f"Non-rect polygon found with {len(poly)} points")

        return ParsedGlyph(
            kind="char",
            key=key,
            char=ch,
            codepoint=cp,
            sequence=None,
            filename=svg_path.name,
            width=width,
            height=height,
            polys=polys,
            rects=rects,
            warnings=warnings,
        )

    # Ligature glyph
    if LIGA_SVG_RE.match(svg_path.name):
        chs, cps, seq_key = _decode_ligature_filename(svg_path.name)

        text = svg_path.read_text(encoding="utf-8")
        root = ET.fromstring(text)

        min_x, min_y, width, height = parse_viewbox(root)
        warnings: List[str] = []

        if abs(min_x) > EPS or abs(min_y) > EPS:
            warnings.append(f"Non-zero viewBox origin ({min_x}, {min_y})")

        polys: List[Poly] = []
        rects: List[Rect] = []

        for elem in root.iter():
            if localname(elem.tag) != "polygon":
                continue
            points_attr = elem.attrib.get("points", "").strip()
            if not points_attr:
                warnings.append("Polygon without points attribute")
                continue

            poly = parse_points_attr(points_attr)
            polys.append(poly)

            if is_axis_aligned_rect(poly):
                rects.append(poly_to_rect(poly))
            else:
                warnings.append(f"Non-rect polygon found with {len(poly)} points")

        return ParsedGlyph(
            kind="liga",
            key=seq_key,     # e.g. "u0073-u0074"
            char=chs,        # e.g. "st"
            codepoint=None,
            sequence=cps,    # e.g. [0x73,0x74]
            filename=svg_path.name,
            width=width,
            height=height,
            polys=polys,
            rects=rects,
            warnings=warnings,
        )

    raise ValueError(f"Unsupported glyph filename: {svg_path.name}")


# -----------------------------
# Grid conversion
# -----------------------------
def x_breaks_for_width(width: float) -> List[int]:
    """
    Extended x-breaks in steps of 4 up to the glyph width.
    Ensures the last break is >= width (rounded to int-ish), and includes 0.
    """
    if abs(width - round(width)) <= EPS:
        w_i = int(round(width))
    else:
        w_i = int(math.ceil(width))

    n = max(1, int(math.ceil(w_i / GRID_STEP_X)))
    breaks = [i * GRID_STEP_X for i in range(n + 1)]  # 0..n*4
    if breaks[-1] < w_i:
        breaks.append(w_i)
    return breaks


def cell_rect(r: int, c: int, x_breaks: Sequence[int]) -> Rect:
    return (float(x_breaks[c]), float(Y_BREAKS[r]), float(x_breaks[c + 1]), float(Y_BREAKS[r + 1]))


def rect_covers_cell(rect: Rect, cell: Rect) -> bool:
    rx1, ry1, rx2, ry2 = rect
    cx1, cy1, cx2, cy2 = cell
    return (
        rx1 <= cx1 + EPS and
        ry1 <= cy1 + EPS and
        rx2 >= cx2 - EPS and
        ry2 >= cy2 - EPS
    )


def grid_for_rects(rects: Sequence[Rect], width: float, x_breaks: Sequence[int]) -> Tuple[List[List[int]], List[List[int]], List[str]]:
    """
    Build a ROWS x COLS occupancy grid based on partition lines (x_breaks + Y_BREAKS).
    Cells outside glyph width are always 0.
    Returns (grid, active_cells, warnings).
    """
    rows = len(Y_BREAKS) - 1
    cols = len(x_breaks) - 1

    grid = [[0 for _ in range(cols)] for _ in range(rows)]
    warnings: List[str] = []

    if abs(width - round(width)) <= EPS:
        width_i = int(round(width))
    else:
        width_i = int(width)
        warnings.append(f"Non-integer glyph width: {width}")

    legal_xs = set(float(x) for x in x_breaks if x <= width_i + EPS)
    legal_ys = set(float(y) for y in Y_BREAKS)

    for rect in rects:
        x1, y1, x2, y2 = rect
        for x in (x1, x2):
            if not any(abs(x - lx) <= EPS for lx in legal_xs):
                warnings.append(f"Rect x-edge off grid: {clean_num(x)} in rect {tuple(clean_num(v) for v in rect)}")
                break
        for y in (y1, y2):
            if not any(abs(y - ly) <= EPS for ly in legal_ys):
                warnings.append(f"Rect y-edge off grid: {clean_num(y)} in rect {tuple(clean_num(v) for v in rect)}")
                break

    for r in range(rows):
        for c in range(cols):
            c_x2 = x_breaks[c + 1]
            if c_x2 > width_i + EPS:
                grid[r][c] = 0
                continue
            cell = cell_rect(r, c, x_breaks)
            if any(rect_covers_cell(rect, cell) for rect in rects):
                grid[r][c] = 1

    active_cells = [[r, c] for r in range(rows) for c in range(cols) if grid[r][c] == 1]
    return grid, active_cells, warnings


# -----------------------------
# Output shaping
# -----------------------------
def unicode_name_safe(ch: str) -> str:
    if ch == "":
        return ""
    try:
        return unicodedata.name(ch)
    except ValueError:
        return "<unnamed>"


def glyph_to_record(g: ParsedGlyph) -> Dict[str, Any]:
    width_units = int(round(g.width / 4)) if abs((g.width / 4) - round(g.width / 4)) <= EPS else None

    # Singles use canonical breaks; ligatures use extended breaks
    if g.kind == "char":
        x_breaks = X_BREAKS
        include_x_breaks = False
    else:
        x_breaks = x_breaks_for_width(g.width)
        include_x_breaks = True

    grid, active_cells, grid_warnings = grid_for_rects(g.rects, g.width, x_breaks)
    all_warnings = list(g.warnings) + list(grid_warnings)

    record: Dict[str, Any] = {
        "kind": g.kind,  # "char" | "liga"
        "key": g.char,   # actual character or ligature string
        "label": "SPACE" if g.char == " " else g.char,
        "file": g.filename,
        "width": clean_num(g.width),
        "height": clean_num(g.height),
        "widthUnits": width_units,
        "polys": [
            [[clean_num(x), clean_num(y)] for (x, y) in poly]
            for poly in g.polys
        ],
        "rects": [
            [clean_num(x1), clean_num(y1), clean_num(x2), clean_num(y2)]
            for (x1, y1, x2, y2) in g.rects
        ],
        "grid": grid,
        "activeCells": active_cells,
    }

    if g.kind == "char":
        assert g.codepoint is not None
        record.update(
            {
                "codepoint": f"U+{g.codepoint:04X}",
                "codepointInt": g.codepoint,
                "unicodeName": unicode_name_safe(g.char),
            }
        )
    else:
        # ligature
        seq = g.sequence or []
        record.update(
            {
                "sequence": seq,
                "sequenceKey": g.key,  # "u0073-u0074"
                "unicodeName": " + ".join(unicode_name_safe(chr(cp)) for cp in seq) if seq else "<unnamed>",
            }
        )
        if include_x_breaks:
            record["xBreaks"] = list(x_breaks)

    if all_warnings:
        seen = set()
        uniq: List[str] = []
        for w in all_warnings:
            if w not in seen:
                seen.add(w)
                uniq.append(w)
        record["warnings"] = uniq

    return record


def build_payload(chars: Sequence[ParsedGlyph], ligs: Sequence[ParsedGlyph], src_dir: Path) -> Dict[str, Any]:
    glyph_map: Dict[str, Any] = {}
    for g in sorted(chars, key=lambda x: x.codepoint or 0):
        glyph_map[g.key] = glyph_to_record(g)

    lig_map: Dict[str, Any] = {}
    for g in sorted(ligs, key=lambda x: (len(x.sequence or []), tuple(x.sequence or []))):
        lig_map[g.key] = glyph_to_record(g)

    by_char = {glyph_map[k]["key"]: k for k in glyph_map.keys()}

    lig_by_key: Dict[str, str] = {}
    lig_by_seq: Dict[str, str] = {}
    for seq_key, rec in lig_map.items():
        lig_by_seq[seq_key] = seq_key
        k = rec.get("key", "")
        if isinstance(k, str) and k and k not in lig_by_key:
            lig_by_key[k] = seq_key

    payload: Dict[str, Any] = {
        "manifestVersion": 1,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "sourceDir": str(src_dir),
        "grid": {
            "xBreaks": X_BREAKS,
            "yBreaks": Y_BREAKS,
            "cellHeight": CELL_H,
            "baselineY": 19,
            "stepX": GRID_STEP_X,
        },
        "glyphCount": len(glyph_map),
        "ligatureCount": len(lig_map),
        "glyphs": glyph_map,
        "ligatures": lig_map,
        "indices": {
            "byChar": by_char,
            "ligaturesByKey": lig_by_key,
            "ligaturesBySequence": lig_by_seq,
        },
    }
    return payload


def write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_python(path: Path, payload: Dict[str, Any]) -> None:
    py_obj_repr = pformat(payload, width=100, sort_dicts=False)

    code = (
        "# Auto-generated by tools/generate-data.py\n"
        "# Do not edit by hand.\n"
        "from __future__ import annotations\n\n"
        f"DATA = {py_obj_repr}\n\n"
        "GLYPHS = DATA['glyphs']\n"
        "LIGATURES = DATA.get('ligatures', {})\n\n"
        "BY_CHAR = DATA['indices']['byChar']\n"
        "LIGATURES_BY_KEY = DATA['indices'].get('ligaturesByKey', {})\n"
        "LIGATURES_BY_SEQUENCE = DATA['indices'].get('ligaturesBySequence', {})\n\n"
        "def get_glyph_by_char(ch: str):\n"
        "    key = BY_CHAR.get(ch)\n"
        "    return GLYPHS.get(key) if key else None\n\n"
        "def get_ligature_by_key(key: str):\n"
        "    seq = LIGATURES_BY_KEY.get(key)\n"
        "    return LIGATURES.get(seq) if seq else None\n\n"
        "def get_ligature_by_sequence(seq_key: str):\n"
        "    return LIGATURES.get(seq_key)\n"
    )
    path.write_text(code, encoding="utf-8")


# -----------------------------
# Main
# -----------------------------
def find_svg_files(src_dir: Path) -> Tuple[List[Path], List[Path]]:
    if not src_dir.exists():
        raise FileNotFoundError(f"Source directory not found: {src_dir}")

    char_files = [p for p in src_dir.iterdir() if p.is_file() and CHAR_SVG_RE.match(p.name)]
    liga_files = [p for p in src_dir.iterdir() if p.is_file() and LIGA_SVG_RE.match(p.name)]

    char_files = sorted(char_files, key=lambda p: int(CHAR_SVG_RE.match(p.name).group(1), 16))  # type: ignore[union-attr]
    liga_files = sorted(liga_files, key=lambda p: p.name.lower())

    return char_files, liga_files


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Generate glyph data (JSON + Python) from SVG glyph files.")
    ap.add_argument("--src", type=Path, default=default_src_dir(), help="Source SVG directory (default: ./src)")
    ap.add_argument("--out", type=Path, default=default_data_dir(), help="Output data directory (default: ./data)")
    ap.add_argument("--strict", action="store_true", help="Fail if warnings are found")
    return ap.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    src_dir: Path = args.src
    out_dir: Path = args.out

    char_files, liga_files = find_svg_files(src_dir)
    if not char_files:
        print(f"No character SVGs found in {src_dir} (expected character-uXXXX.svg files).", file=sys.stderr)
        return 1

    parsed_chars: List[ParsedGlyph] = []
    parsed_ligs: List[ParsedGlyph] = []

    for svg_path in char_files:
        try:
            g = parse_svg_file(svg_path)
        except Exception as e:
            print(f"[ERROR] {svg_path.name}: {e}", file=sys.stderr)
            return 1
        parsed_chars.append(g)

    for svg_path in liga_files:
        try:
            g = parse_svg_file(svg_path)
        except Exception as e:
            print(f"[ERROR] {svg_path.name}: {e}", file=sys.stderr)
            return 1
        parsed_ligs.append(g)

    payload = build_payload(parsed_chars, parsed_ligs, src_dir)

    expanded_warning_count = 0
    for rec in payload["glyphs"].values():
        expanded_warning_count += len(rec.get("warnings", []))
    for rec in payload.get("ligatures", {}).values():
        expanded_warning_count += len(rec.get("warnings", []))

    if args.strict and expanded_warning_count:
        print(f"[STRICT] Found {expanded_warning_count} warning(s). Aborting.", file=sys.stderr)
        return 2

    out_dir.mkdir(parents=True, exist_ok=True)

    json_path = out_dir / "glyphs.json"
    py_path = out_dir / "glyphs.py"

    write_json(json_path, payload)
    write_python(py_path, payload)

    print(f"Wrote {payload['glyphCount']} glyphs + {payload.get('ligatureCount', 0)} ligatures:")
    print(f"  - {json_path}")
    print(f"  - {py_path}")

    if payload.get("ligatureCount", 0):
        print("Ligatures indexed (by key):", ", ".join(sorted(payload["indices"]["ligaturesByKey"].keys())))

    if expanded_warning_count:
        print(f"\nWarnings detected in {expanded_warning_count} record(s) (see 'warnings' fields in output).")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())