#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
tools/generate-data.py

Reverse glyph data exporter for the custom SVG glyph format.

Reads:
  src/character-u{codepoint}.svg

Writes:
  data/glyphs.json
  data/glyphs.py

What it extracts per glyph:
- character / codepoint metadata
- width / height (from SVG viewBox)
- raw polygon points
- rectangle form (x1,y1,x2,y2) when polygons are axis-aligned rectangles
- grid occupancy based on the known MMXX-style partition grid
- active cell coordinates

This is designed to work with glyphs generated by your current SVG generator
(and also with manually edited/exported glyphs from the glyph designer).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import unicodedata
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from pprint import pformat
from typing import Any, Dict, Iterable, List, Sequence, Tuple

# -----------------------------
# Known grid (from your typeface system)
# -----------------------------
X_BREAKS = [0, 4, 8, 12, 16, 20]
Y_BREAKS = [0, 1, 4, 9, 10, 14, 15, 19, 20, 25, 29, 30]
CELL_H = 30

# Small tolerance for float parsing / comparisons (in case edited SVGs contain "12.0")
EPS = 1e-9

SVG_FILE_RE = re.compile(r"^character-u([0-9a-fA-F]+)\.svg$")


Point = Tuple[float, float]
Poly = List[Point]
Rect = Tuple[float, float, float, float]


@dataclass
class ParsedGlyph:
    key: str                  # e.g. "u0061"
    char: str                 # e.g. "a"
    codepoint: int            # e.g. 97
    filename: str             # e.g. "character-u0061.svg"
    width: float
    height: float
    polys: List[Poly]
    rects: List[Rect]
    warnings: List[str]


# -----------------------------
# Path helpers
# -----------------------------
def project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def default_src_dir() -> Path:
    return project_root() / "src"


def default_data_dir() -> Path:
    return project_root() / "data"


# -----------------------------
# Parsing helpers
# -----------------------------
def localname(tag: str) -> str:
    return tag.split("}", 1)[-1] if "}" in tag else tag


def parse_number(s: str) -> float:
    try:
        return float(s)
    except ValueError as e:
        raise ValueError(f"Invalid numeric value in SVG points: {s!r}") from e


def clean_num(n: float) -> int | float:
    """Convert integral floats to int for cleaner output."""
    if abs(n - round(n)) <= EPS:
        return int(round(n))
    return n


def parse_points_attr(points_attr: str) -> Poly:
    """
    Parse SVG polygon points:
      "x1,y1 x2,y2 x3,y3 ..."
    Also tolerates commas/spaces mixed.
    """
    tokens = points_attr.replace(",", " ").split()
    if len(tokens) % 2 != 0:
        raise ValueError(f"Odd number of coordinates in points attribute: {points_attr!r}")

    pts: Poly = []
    for i in range(0, len(tokens), 2):
        x = parse_number(tokens[i])
        y = parse_number(tokens[i + 1])
        pts.append((x, y))
    return pts


def parse_viewbox(root: ET.Element) -> Tuple[float, float, float, float]:
    vb = root.attrib.get("viewBox")
    if vb:
        parts = vb.replace(",", " ").split()
        if len(parts) != 4:
            raise ValueError(f"Invalid viewBox: {vb!r}")
        return tuple(parse_number(p) for p in parts)  # type: ignore[return-value]

    # Fallback to width/height if no viewBox (less ideal)
    w = root.attrib.get("width")
    h = root.attrib.get("height")
    if w is None or h is None:
        raise ValueError("SVG is missing both viewBox and width/height.")
    return (0.0, 0.0, parse_number(w), parse_number(h))


def is_axis_aligned_rect(poly: Poly) -> bool:
    if len(poly) != 4:
        return False
    xs = {round(p[0], 9) for p in poly}
    ys = {round(p[1], 9) for p in poly}
    return len(xs) == 2 and len(ys) == 2


def poly_to_rect(poly: Poly) -> Rect:
    xs = [p[0] for p in poly]
    ys = [p[1] for p in poly]
    return (min(xs), min(ys), max(xs), max(ys))


def parse_svg_file(svg_path: Path) -> ParsedGlyph:
    m = SVG_FILE_RE.match(svg_path.name)
    if not m:
        raise ValueError(f"Unsupported glyph filename: {svg_path.name}")

    hex_cp = m.group(1).lower()
    cp = int(hex_cp, 16)
    ch = chr(cp)
    key = f"u{hex_cp}"

    text = svg_path.read_text(encoding="utf-8")
    root = ET.fromstring(text)

    min_x, min_y, width, height = parse_viewbox(root)
    warnings: List[str] = []

    if abs(min_x) > EPS or abs(min_y) > EPS:
        warnings.append(f"Non-zero viewBox origin ({min_x}, {min_y})")

    polys: List[Poly] = []
    rects: List[Rect] = []

    for elem in root.iter():
        if localname(elem.tag) != "polygon":
            continue
        points_attr = elem.attrib.get("points", "").strip()
        if not points_attr:
            warnings.append("Polygon without points attribute")
            continue

        poly = parse_points_attr(points_attr)
        polys.append(poly)

        if is_axis_aligned_rect(poly):
            rects.append(poly_to_rect(poly))
        else:
            warnings.append(f"Non-rect polygon found with {len(poly)} points")

    return ParsedGlyph(
        key=key,
        char=ch,
        codepoint=cp,
        filename=svg_path.name,
        width=width,
        height=height,
        polys=polys,
        rects=rects,
        warnings=warnings,
    )


# -----------------------------
# Grid conversion
# -----------------------------
def cell_rect(r: int, c: int) -> Rect:
    return (X_BREAKS[c], Y_BREAKS[r], X_BREAKS[c + 1], Y_BREAKS[r + 1])


def rect_covers_cell(rect: Rect, cell: Rect) -> bool:
    rx1, ry1, rx2, ry2 = rect
    cx1, cy1, cx2, cy2 = cell
    return (
        rx1 <= cx1 + EPS and
        ry1 <= cy1 + EPS and
        rx2 >= cx2 - EPS and
        ry2 >= cy2 - EPS
    )


def grid_for_rects(rects: Sequence[Rect], width: float) -> Tuple[List[List[int]], List[List[int]], List[str]]:
    """
    Build a ROWS x COLS occupancy grid based on known partition lines.
    Cells outside glyph width are always 0.
    Returns (grid, active_cells, warnings).
    """
    rows = len(Y_BREAKS) - 1
    cols = len(X_BREAKS) - 1

    grid = [[0 for _ in range(cols)] for _ in range(rows)]
    warnings: List[str] = []

    # Width should be one of 4, 8, 12, 16, 20 in this system, but we won't hard-fail.
    if abs(width - round(width)) <= EPS:
        width_i = int(round(width))
    else:
        width_i = int(width)
        warnings.append(f"Non-integer glyph width: {width}")

    # Check alignment to known grid (optional warning only)
    legal_xs = set(float(x) for x in X_BREAKS if x <= width_i + EPS)
    legal_ys = set(float(y) for y in Y_BREAKS)

    for rect in rects:
        x1, y1, x2, y2 = rect
        for x in (x1, x2):
            if not any(abs(x - lx) <= EPS for lx in legal_xs):
                warnings.append(f"Rect x-edge off grid: {clean_num(x)} in rect {tuple(clean_num(v) for v in rect)}")
                break
        for y in (y1, y2):
            if not any(abs(y - ly) <= EPS for ly in legal_ys):
                warnings.append(f"Rect y-edge off grid: {clean_num(y)} in rect {tuple(clean_num(v) for v in rect)}")
                break

    for r in range(rows):
        for c in range(cols):
            c_x2 = X_BREAKS[c + 1]
            if c_x2 > width_i + EPS:
                grid[r][c] = 0
                continue
            cell = cell_rect(r, c)
            if any(rect_covers_cell(rect, cell) for rect in rects):
                grid[r][c] = 1

    active_cells = [[r, c] for r in range(rows) for c in range(cols) if grid[r][c] == 1]
    return grid, active_cells, warnings


# -----------------------------
# Output shaping
# -----------------------------
def unicode_name_safe(ch: str) -> str:
    if ch == "":
        return ""
    try:
        return unicodedata.name(ch)
    except ValueError:
        return "<unnamed>"


def glyph_to_record(g: ParsedGlyph) -> Dict[str, Any]:
    width_units = int(round(g.width / 4)) if abs((g.width / 4) - round(g.width / 4)) <= EPS else None

    grid, active_cells, grid_warnings = grid_for_rects(g.rects, g.width)

    all_warnings = list(g.warnings) + list(grid_warnings)

    record: Dict[str, Any] = {
        "key": g.char,
        "label": "SPACE" if g.char == " " else g.char,
        "codepoint": f"U+{g.codepoint:04X}",
        "codepointInt": g.codepoint,
        "unicodeName": unicode_name_safe(g.char),
        "file": g.filename,
        "width": clean_num(g.width),
        "height": clean_num(g.height),
        "widthUnits": width_units,
        "polys": [
            [[clean_num(x), clean_num(y)] for (x, y) in poly]
            for poly in g.polys
        ],
        "rects": [
            [clean_num(x1), clean_num(y1), clean_num(x2), clean_num(y2)]
            for (x1, y1, x2, y2) in g.rects
        ],
        "grid": grid,
        "activeCells": active_cells,
    }

    if all_warnings:
        # de-duplicate but preserve order
        seen = set()
        uniq: List[str] = []
        for w in all_warnings:
            if w not in seen:
                seen.add(w)
                uniq.append(w)
        record["warnings"] = uniq

    return record


def build_payload(glyphs: Sequence[ParsedGlyph], src_dir: Path) -> Dict[str, Any]:
    glyph_map: Dict[str, Any] = {}

    for g in sorted(glyphs, key=lambda x: x.codepoint):
        glyph_map[g.key] = glyph_to_record(g)

    # Convenience index by actual character (JSON keys can be spaces, so this is okay)
    by_char = {glyph_map[k]["key"]: k for k in glyph_map.keys()}

    payload: Dict[str, Any] = {
        "manifestVersion": 1,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "sourceDir": str(src_dir),
        "grid": {
            "xBreaks": X_BREAKS,
            "yBreaks": Y_BREAKS,
            "cellHeight": CELL_H,
            "baselineY": 19,
        },
        "glyphCount": len(glyph_map),
        "glyphs": glyph_map,
        "indices": {
            "byChar": by_char,
        },
    }
    return payload


def write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_python(path: Path, payload: Dict[str, Any]) -> None:
    # Pretty-print a Python-literal equivalent of the JSON payload
    py_obj_repr = pformat(payload, width=100, sort_dicts=False)

    code = (
        "# Auto-generated by tools/generate-data.py\n"
        "# Do not edit by hand.\n"
        "from __future__ import annotations\n\n"
        f"DATA = {py_obj_repr}\n\n"
        "GLYPHS = DATA['glyphs']\n"
        "BY_CHAR = DATA['indices']['byChar']\n\n"
        "def get_glyph_by_char(ch: str):\n"
        "    key = BY_CHAR.get(ch)\n"
        "    return GLYPHS.get(key) if key else None\n"
    )
    path.write_text(code, encoding="utf-8")


# -----------------------------
# Main
# -----------------------------
def find_svg_files(src_dir: Path) -> List[Path]:
    if not src_dir.exists():
        raise FileNotFoundError(f"Source directory not found: {src_dir}")

    files = [p for p in src_dir.iterdir() if p.is_file() and SVG_FILE_RE.match(p.name)]
    return sorted(files, key=lambda p: int(SVG_FILE_RE.match(p.name).group(1), 16))  # type: ignore[union-attr]


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Generate glyph data (JSON + Python) from SVG glyph files.")
    ap.add_argument("--src", type=Path, default=default_src_dir(), help="Source SVG directory (default: ./src)")
    ap.add_argument("--out", type=Path, default=default_data_dir(), help="Output data directory (default: ./data)")
    ap.add_argument("--strict", action="store_true", help="Fail if warnings are found")
    return ap.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    src_dir: Path = args.src
    out_dir: Path = args.out

    svg_files = find_svg_files(src_dir)
    if not svg_files:
        print(f"No character SVGs found in {src_dir} (expected character-uXXXX.svg files).", file=sys.stderr)
        return 1

    parsed: List[ParsedGlyph] = []
    total_warnings = 0

    for svg_path in svg_files:
        try:
            g = parse_svg_file(svg_path)
        except Exception as e:
            print(f"[ERROR] {svg_path.name}: {e}", file=sys.stderr)
            return 1

        parsed.append(g)
        total_warnings += len(g.warnings)

    payload = build_payload(parsed, src_dir)

    # Count warnings after grid validation too
    expanded_warning_count = 0
    for rec in payload["glyphs"].values():
        expanded_warning_count += len(rec.get("warnings", []))

    if args.strict and expanded_warning_count:
        print(f"[STRICT] Found {expanded_warning_count} warning(s). Aborting.", file=sys.stderr)
        return 2

    out_dir.mkdir(parents=True, exist_ok=True)

    json_path = out_dir / "glyphs.json"
    py_path = out_dir / "glyphs.py"

    write_json(json_path, payload)
    write_python(py_path, payload)

    print(f"Wrote {len(payload['glyphs'])} glyphs:")
    print(f"  - {json_path}")
    print(f"  - {py_path}")

    if expanded_warning_count:
        print(f"\nWarnings detected in {expanded_warning_count} record(s) (see 'warnings' fields in output).")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())